# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhQ0kAW5YypaZJh2dwuAsdi5TJVK2oyS
"""

# 1. Install dependencies
!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

# 2. Explicitly target the logon file within the CERT dataset repository
file_path = "logon.csv"

# 3. Load using the updated dataset_load function
df_raw = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "mrajaxnp/cert-insider-threat-detection-research",
    file_path
)

print("Data successfully pulled from CERT Kaggle source!")
print(f"Total raw log events loaded: {len(df_raw)}")
print(df_raw.head())

import pandas as pd

# Standardize column naming conventions to lowercase
df_raw.columns = df_raw.columns.str.lower()

# Parse timestamps cleanly
df_raw['date'] = pd.to_datetime(df_raw['date'], format='%m/%d/%Y %H:%M:%S')

# Capture hours and convert dates to single day strings
df_raw['hour'] = df_raw['date'].dt.hour
df_raw['day_string'] = df_raw['date'].dt.strftime('%Y-%m-%d')

# Identify activity occurring outside standard 6 AM to 6 PM hours
df_raw['is_off_hours'] = df_raw['hour'].apply(lambda x: 1 if (x < 6 or x > 18) else 0)

# Build daily baseline metrics per user
daily_profiles = df_raw.groupby(['user', 'day_string']).agg(
    total_events=('activity', 'count'),
    off_hours_events=('is_off_hours', 'sum'),
    avg_hour=('hour', 'mean'),
    unique_pcs=('pc', 'nunique')
).reset_index()

print("Aggregation complete! Behavioral Profiles generated:")
print(daily_profiles.head())

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Extract numerical columns for AI evaluation
feature_cols = ['total_events', 'off_hours_events', 'avg_hour', 'unique_pcs']
X = daily_profiles[feature_cols]

# Scale features so that heavy log volume numbers don't overwhelm timeline hours
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Define an expected extreme anomaly rate of 0.5% (contamination=0.005)
model = IsolationForest(contamination=0.005, random_state=42)
daily_profiles['anomaly_score'] = model.fit(X_scaled).score_samples(X_scaled)
daily_profiles['is_threat'] = model.predict(X_scaled)

# Normalize labels: 1 = Threat Flag, 0 = Normal Baseline
daily_profiles['is_threat'] = daily_profiles['is_threat'].apply(lambda x: 1 if x == -1 else 0)

print(f"CyberShield analysis complete. Flagged {daily_profiles['is_threat'].sum()} critical threats.")

threat_alerts = daily_profiles[daily_profiles['is_threat'] == 1].sort_values(by='anomaly_score')
print("CYBERSHIELD AI PLATFORM: INCIDENT RESPONSE AUDIT REPORT")
print("-" * 70)
if len(threat_alerts) == 0:
    print("System Status: Healthy. Zero anomalies detected.")
else:
    for idx, alert in threat_alerts.head(5).iterrows():
        print(f"ALERT: Malicious/Anomalous Signature Detected")
        print(f"Account Username:    {alert['user']}")
        print(f"Target Date:          {alert['day_string']}")
        print(f"Diagnostic Breakdown:")
        print(f"  - Action Footprint:   {alert['total_events']} events tracked")
        print(f"  - Off-Hours Activity: {alert['off_hours_events']} logs outside 6AM-6PM")
        print(f"  - Terminal Scans:     Used {alert['unique_pcs']} unique workstation(s)")
        print(f"Model Surprise Factor Score: {abs(alert['anomaly_score']):.4f}")
        print("-" * 70)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(11, 6))

# Plot normal behavior in crisp blue
sns.scatterplot(
    data=daily_profiles[daily_profiles['is_threat'] == 0],
    x='total_events', y='off_hours_events',
    alpha=0.4, label='Normal Baseline Activity', color='dodgerblue'
)

# Overlay the threats intercepted by CyberShield in vivid red
sns.scatterplot(
    data=daily_profiles[daily_profiles['is_threat'] == 1],
    x='total_events', y='off_hours_events',
    color='crimson', s=130, marker='X', label='CyberShield Threat Flag'
)

plt.title('CyberShield AI: Behavior Anomaly Distribution (CERT Logs)', fontsize=14, fontweight='bold')
plt.xlabel('Total Interaction Events (Logon/Logoff Volume)', fontsize=11)
plt.ylabel('Off-Hours Incidents (Outside 6 AM - 6 PM)', fontsize=11)
plt.legend(frameon=True, shadow=True, facecolor='white')
plt.grid(True, linestyle=':', alpha=0.5)
plt.show()

# Isolate entries flagged as threats, sorted by highest anomaly severity
threat_alerts = daily_profiles[daily_profiles['is_threat'] == 1].sort_values(by='anomaly_score')

# Compile and save the critical alerts to a standalone file
log_filename = "cybershield_incident_log.txt"

with open(log_filename, "w", encoding="utf-8") as f:
    f.write("CYBERSHIELD AI PLATFORM: ENTERPRISE INCIDENT AUDIT REPOSITORY\n")
    f.write(f"Report Generated: Active Threat Queue contains {len(threat_alerts)} anomalies.\n")
    f.write("-" * 70 + "\n\n")

    for idx, alert in threat_alerts.iterrows():
        f.write(f"ALERT IDENTIFIER: [CS-ANOMALY-{idx}]\n")
        f.write(f"Account Username:             {alert['user']}\n")
        f.write(f"Event Signature Timeline:     {alert['day_string']}\n")
        f.write(f"Diagnostic Profile Analytics:\n")
        f.write(f"  - Action Footprint:           {int(alert['total_events'])} logon/logoff operations\n")
        f.write(f"  - Off-Hours Activity Counter: {int(alert['off_hours_events'])} items outside 6AM-6PM\n")
        f.write(f"  - Terminal Scans:             Accessed {int(alert['unique_pcs'])} unique workstation(s)\n")
        f.write(f"Model Threat Surprise Factor: {abs(alert['anomaly_score']):.4f}\n")
        f.write("-" * 70 + "\n")

print(f"Success! Security logs compiled and exported to '{log_filename}'!")
print("Click the folder icon on the left sidebar in Colab to view or download it.")

def trigger_automated_mitigation(user_id, unique_pcs, off_hours_events):
    """
    Simulates automated security orchestration and response (SOAR) playbooks.
    """
    print(f"Initiating CyberShield Proactive Mitigation for: {user_id}")

    # Policy 1: Lateral Movement Defense (Terminal Hopping)
    if unique_pcs >= 6:
        print(f"   [VIOLATION]: Account accessed {unique_pcs} different workstations in 24 hours.")
        print(f"   [ACTION]: TERMINATED active remote desktop sessions. Locking account to home domain.")

    # Policy 2: Data Exfiltration Defense (Off-Hours Activity)
    if off_hours_events > 10:
        print(f"   [VIOLATION]: Highly concentrated off-hours footprint ({off_hours_events} actions outside window).")
        print(f"   [ACTION]: Revoking active OAuth access tokens and forcing step-up Multi-Factor Authentication.")
    print("-" * 80)


# Trigger the automated playbooks for the top critical alerts found by your model
print("\nTriggers tripped. Executing automated playbooks for highest-risk assets:\n")
for idx, alert in threat_alerts.head(3).iterrows():
    trigger_automated_mitigation(alert['user'], alert['unique_pcs'], alert['off_hours_events'])

